version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile
    image: sandboxapp
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
  webserver:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile_Nginx
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/app
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app